// Generated by AppForge — Maximoney
class AppConfig {
  static const String appforgeApiBaseUrl = 'https://flutteradmin.valuecreateventures.top';
  static const String appId   = '24984694-8a1d-47ba-a0cf-1a94e9b99839';
  static const String appName = 'Maximoney';
  static const String fallbackUrl        = 'https://credit.maximoney.in';
  static const String fallbackThemeColor = '#1DBF98';
  static const String fallbackAccent     = '#1DBF98';
  static const bool splashShowText   = true;
  static const int  splashDurationMs = 1500;
  static const String playStoreUrl = '';
  static const String appStoreUrl  = '';
  static const String whatsappShareMessage = 'Check out Maximoney';
  static const String admobAppId        = 'ca-app-pub-3940256099942544~3347511713';
  static const String admobBannerUnitId = 'ca-app-pub-3940256099942544/6300978111';
  static const int ratingPromptAfterSessions = 5;
  static const String notifChannelTransactional = 'transactional';
  static const String notifChannelPromotional   = 'promotional';
  static const String notifChannelAlerts        = 'alerts';
}
