// GET /api/generator/:appId — downloads configured Flutter project as ZIP.
//
// Reads the sibling `flutter_shell/` directory, applies per-app
// substitutions (package name, app host, AdMob ID, etc.), injects a
// freshly-generated lib/app_config.dart, and streams the ZIP back.

import { NextRequest, NextResponse } from 'next/server';
import JSZip from 'jszip';

import { getServerClient } from '@/lib/supabase/server';
import type { App } from '@/lib/supabase/types';
import {
  applySubstitutions,
  flutterShellRoot,
  walkFlutterShell,
} from '@/lib/generator/template';

export const runtime = 'nodejs';

function escapeDart(s: string | null | undefined): string {
  return (s ?? '').replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');
}

function generateAppConfig(app: App): string {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://admin.yourdomain.com';
  return `// Generated by AppForge — ${app.name}
// Edit the fields here or use the admin panel to change remotely.

class AppConfig {
  // AppForge backend (shared across all apps)
  static const String appforgeApiBaseUrl = '${baseUrl}';

  // Unique app identity
  static const String appId   = '${app.id}';
  static const String appName = '${escapeDart(app.name)}';

  // Fallbacks when AppForge is unreachable
  static const String fallbackUrl        = '${escapeDart(app.app_url)}';
  static const String fallbackThemeColor = '${app.theme_primary}';
  static const String fallbackAccent     = '${app.theme_accent}';

  // Splash fallbacks — admin panel overrides these at runtime
  static const bool splashShowText   = ${app.splash_enabled};
  static const int  splashDurationMs = ${app.splash_duration_ms};

  // Store links (filled after publish)
  static const String playStoreUrl = '${escapeDart(app.play_store_url)}';
  static const String appStoreUrl  = '${escapeDart(app.app_store_url)}';

  // Share
  static const String whatsappShareMessage = 'Check out ${escapeDart(app.name)}';

  // AdMob (only used when enabled in admin)
  static const String admobAppId        = '${escapeDart(app.admob_app_id) || 'ca-app-pub-3940256099942544~3347511713'}';
  static const String admobBannerUnitId = '${escapeDart(app.admob_banner_unit_id) || 'ca-app-pub-3940256099942544/6300978111'}';

  // Rating prompt
  static const int ratingPromptAfterSessions = 5;

  // Notification channels
  static const String notifChannelTransactional = 'transactional';
  static const String notifChannelPromotional   = 'promotional';
  static const String notifChannelAlerts        = 'alerts';
}
`;
}

function generateReadme(app: App): string {
  const host = (() => {
    try { return new URL(app.app_url).host; } catch { return 'example.com'; }
  })();

  return `# ${app.name}

Generated by AppForge on ${new Date().toISOString().split('T')[0]}.

## App identity
- **Name:** ${app.name}
- **Package:** \`${app.package_name}\`
- **Bundle ID:** \`${app.bundle_id || app.package_name}\`
- **URL:** ${app.app_url}
- **AppForge App ID:** \`${app.id}\`

## Setup

\`\`\`bash
# 1. Install dependencies
flutter pub get

# 2. Connect Firebase (shared push project)
flutterfire configure --project=<shared-firebase-project-id> --platforms=android,ios

# 3. Generate Android keystore (once, reuse across apps if you like)
keytool -genkey -v -keystore ~/Desktop/${app.slug}-keystore.jks \\
  -keyalg RSA -keysize 2048 -validity 10000 -alias ${app.slug}

# 4. Copy the template and fill in keystore paths:
cp android/key.properties.template android/key.properties
# then edit android/key.properties

# 5. Build
flutter build appbundle --release   # for Play Store
flutter build apk --release         # for phone testing
\`\`\`

## Change config remotely

Visit the AppForge admin panel → this app → Config. Changes propagate
to all users on their next app open (within 60 seconds).

## App Links verification

Host this file at \`https://${host}/.well-known/assetlinks.json\`:

\`\`\`bash
cat docs/hosting/assetlinks_TEMPLATE.json
\`\`\`

If \`sha256_fingerprint\` is missing, run:

\`\`\`bash
keytool -list -v -keystore ~/Desktop/${app.slug}-keystore.jks -alias ${app.slug}
\`\`\`

...and paste the SHA256 into the JSON before hosting.
`;
}

export async function GET(
  _: NextRequest,
  { params }: { params: { appId: string } }
) {
  const supabase = getServerClient();
  const { data: app, error } = await supabase
    .from('apps')
    .select('*')
    .eq('id', params.appId)
    .maybeSingle<App>();

  if (error || !app) {
    return NextResponse.json({ error: 'App not found' }, { status: 404 });
  }

  // 1. Read the Flutter shell template from disk
  let templateFiles: Map<string, Buffer>;
  try {
    const root = flutterShellRoot();
    templateFiles = await walkFlutterShell(root);
    if (templateFiles.size === 0) {
      throw new Error('Empty template');
    }
  } catch (e) {
    console.error('[generator] failed to read flutter_shell:', e);
    return NextResponse.json(
      { error: 'Flutter template not available on server. Check FLUTTER_SHELL_PATH.' },
      { status: 500 }
    );
  }

  // 2. Apply per-app substitutions (path renames + content edits)
  const processed = applySubstitutions(app, templateFiles);

  // 3. Inject generated files
  const zip = new JSZip();
  for (const [relPath, buf] of processed) {
    zip.file(relPath, buf);
  }
  zip.file('lib/app_config.dart', generateAppConfig(app));
  zip.file('README.md',           generateReadme(app));
  zip.file('.appforge-app-id',    app.id);

  const buffer = await zip.generateAsync({ type: 'uint8array' });

  return new NextResponse(buffer as unknown as BodyInit, {
    status: 200,
    headers: {
      'Content-Type':        'application/zip',
      'Content-Disposition': `attachment; filename="${app.slug}-flutter.zip"`,
    },
  });
}
