// Per-app constants. This file is REGENERATED by the AppForge backend
// (see admin_panel/app/api/generator/[appId]/route.ts) when a developer
// downloads the Flutter ZIP. The values below are placeholders for
// standalone development / testing.
//
// DO NOT edit fields here for production — change them in the admin
// panel and download a fresh ZIP, OR edit them remotely (most fields
// are actually served from /api/config/:appId at runtime).

class AppConfig {
  // AppForge backend (shared across all apps)
  static const String appforgeApiBaseUrl = 'https://admin.yourdomain.com';

  // Unique app identity — OVERWRITTEN per app by the generator
  static const String appId   = '00000000-0000-0000-0000-000000000000';
  static const String appName = 'App Template';

  // Fallbacks when AppForge is unreachable (first launch, offline)
  static const String fallbackUrl        = 'https://example.com';
  static const String fallbackThemeColor = '#1A1A2E';
  static const String fallbackAccent     = '#E94560';

  // Splash fallbacks — admin panel overrides these at runtime
  static const bool splashShowText   = true;
  static const int  splashDurationMs = 2000;

  // Store links (filled after publish)
  static const String playStoreUrl = '';
  static const String appStoreUrl  = '';

  // Share
  static const String whatsappShareMessage = 'Check out App Template';

  // AdMob — Google's official test IDs (REPLACE with real IDs before publishing)
  // https://developers.google.com/admob/android/test-ads
  static const String admobAppId        = 'ca-app-pub-3940256099942544~3347511713';
  static const String admobBannerUnitId = 'ca-app-pub-3940256099942544/6300978111';

  // Rating prompt after N sessions
  static const int ratingPromptAfterSessions = 5;

  // Notification channels (used for both Android channels and FCM topic names)
  static const String notifChannelTransactional = 'transactional';
  static const String notifChannelPromotional   = 'promotional';
  static const String notifChannelAlerts        = 'alerts';
}
